language: python
python:
  - "3.6"
  - "3.7"
# command to install dependencies
install:
  - pip install pip -U
  - pip install -r requirements.txt
  - python setup.py install
# command to run tests
script: python test/test_core.py
