[tool.poetry]
name = "peakipy"
version = "0.1.17"
description = "Deconvolute overlapping NMR peaks"
authors = ["Jacob Brady <jacob.brady0449@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.6"
pandas = "^0.24.0"
numpy = "^1.16"
matplotlib = "^3.0"
PyYAML = "^3.13"
nmrglue = "^0.6.0"
scipy = "^1.2"
docopt = "^0.6.2"
lmfit = "^0.9.12"
scikit-image= "^0.14.2"
bokeh = "^1.0.4"
schema = "^0.7.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

[tool.poetry.scripts]
read_peaklist = 'peakipy:scripts.read_peaklist'
fit_peaks = 'peakipy:scripts.fit_peaks'
check_fits = 'peakipy:scripts.check_fits'
edit_fits_script = 'peakipy:scripts.edit_fits_script'
edit_fits = 'peakipy:scripts.edit_fits'
spec = 'peakipy:scripts.spec'
